#!/bin/bash
# alphafold3 RGI example -- centroid distance -> 25.0 A (QBP)
# MSA is generated by the local data pipeline.
# GPU only: run on a GPU compute node (not a shared login node).
# Requires the alphafold3_restr checkout to exist as a sibling of RGI-toolkit/.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
WS="$HERE"; while [ "$WS" != / ] && [ ! -d "$WS/RGI-toolkit" ]; do WS="$(dirname "$WS")"; done
source "$WS/alphafold3_restr/.venv/bin/activate"
cd "$HERE"
MODEL_DIR="${MODEL_DIR:?set MODEL_DIR to your AF3 model-parameters directory}"
DB_DIR="${DB_DIR:?set DB_DIR to your AF3 sequence-database directory}"
export JAX_COMPILATION_CACHE_DIR="${JAX_COMPILATION_CACHE_DIR:-/tmp/${USER}_jax_cache}"
python "$WS/alphafold3_restr/run_alphafold.py" \
    --num_diffusion_samples=1 --run_data_pipeline=True --model_dir="$MODEL_DIR" --db_dir="$DB_DIR" \
    --json_path=qbp_25.00.json --output_dir=out
# Local fallback (skip the DB search): add
#   "unpairedMsaPath": "/path/to/precomputed.a3m"
# to the protein object in qbp_25.00.json, then pass --run_data_pipeline=False.
